### ISSUE TITLE
Disable eslint rule `vue/multi-word-component-names`

### ISSUE THREAD

**Issue by ItsPierre** [jojomatik/nuxt-3-base#171]
**Is your feature request related to a problem? Please describe.**
This rule is blocking components like `Snackbar`, which is a valid name.

**Describe the solution you'd like**
Disable this eslint rule to support more component names.

**Additional context**
[Rule link.](https://eslint.vuejs.org/rules/multi-word-component-names.html)

**Comment by jojomatik** [comment]
Hi @ItsPierre, thanks for opening this issue and sorry for the late reply.

I've since done some digging and while I somewhat agree with you that this might be tedious for certain basic components, I do have to agree with the vue docs. These declare this rule as priority A in their style guide: https://vuejs.org/style-guide/rules-essential.html

The argument being that using multi word comonent names prevents name colissions with future html elements. I will therefore close this issue and suggest coming up with multi word component names OR adding an eslint-disable to the specific component instead of disabling the rule globally.
